[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log ; Log principal do supervisor

[program:xvfb]
command=Xvfb :1 -screen 0 1024x768x24
autorestart=true
startsecs=3

[program:fluxbox]
command=fluxbox
autorestart=true
startsecs=3
environment=DISPLAY=:1

[program:x11vnc]
command=x11vnc -forever -usepw -display :1
autorestart=true
startsecs=3
environment=DISPLAY=:1

[program:oil_hmi]
command=/app/plants/oil-refinery/oil_hmi.py -t localhost
autorestart=true
startsecs=3
environment=DISPLAY=:1

[program:oil_world]
command=/app/plants/oil-refinery/oil_world.py -t localhost
autorestart=true
startsecs=3
environment=DISPLAY=:1
stdout_logfile=/var/log/oil_world_stdout.log
stderr_logfile=/var/log/oil_world_stderr.log


