[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log ; Log principal do supervisor

[program:Xvfb]
command=Xvfb :1 -screen 0 1024x768x24
stdout_logfile=/var/log/supervisor/Xvfb.log
stderr_logfile=/var/log/supervisor/Xvfb_error.log
autorestart=true
startsecs=3
environment=DISPLAY=":1"

[program:fluxbox]
command=fluxbox
stdout_logfile=/var/log/supervisor/fluxbox.log
stderr_logfile=/var/log/supervisor/fluxbox_error.log
autorestart=true
startsecs=3
environment=DISPLAY=":1"

[program:x11vnc]
command=x11vnc -forever -nopw -display :1 -rfbport 5901
stdout_logfile=/var/log/supervisor/x11vnc.log
stderr_logfile=/var/log/supervisor/x11vnc_error.log
autorestart=true
startsecs=3
environment=DISPLAY=":1"

[program:noVNC]
command=/app/noVNC/utils/novnc_proxy --vnc localhost:5901 --listen 6080
stdout_logfile=/var/log/supervisor/novnc.log
stderr_logfile=/var/log/supervisor/novnc_error.log
autorestart=true

[program:oil_world]
command=/app/plants/oil-refinery/oil_world.py -t localhost
autorestart=true
startsecs=3
environment=DISPLAY=:1
stdout_logfile=/var/log/oil_world_stdout.log
stderr_logfile=/var/log/oil_world_stderr.log

# [program:oil_hmi]
# command=/app/plants/oil-refinery/oil_hmi.py -t localhost
# autorestart=true
# startsecs=3
# environment=DISPLAY=:1
# stdout_logfile=/var/log/oil_world_stdout.log
# stderr_logfile=/var/log/oil_world_stderr.log
