[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
loglevel=info
user=root  ; Adicione esta linha para especificar o usuário

; Programa VNC Server
[program:vnc_server]
command=/app/start_vnc.sh
stdout_logfile=/var/log/supervisor/vnc_server.log
stderr_logfile=/var/log/supervisor/vnc_server_error.log
startsecs=7
priority=1

; Programa noVNC Proxy
[program:novnc_proxy]
command=/app/noVNC/utils/novnc_proxy --vnc localhost:5901 --listen 80
stdout_logfile=/var/log/supervisor/novnc_proxy.log
stderr_logfile=/var/log/supervisor/novnc_proxy_error.log
startsecs=7
priority=2

; Programa Flag Manager
[program:flag_manager]
directory=/app/plants/oil-refinery
command=bash -c 'while ! timeout 1 bash -c "</dev/tcp/localhost/5020"; do sleep 1; done; ./flag_manager.py'
stdout_logfile=/var/log/supervisor/flag_manager.log
stderr_logfile=/var/log/supervisor/flag_manager_error.log
startsecs=7
priority=3

; Programa Plant Manager
[program:plant_manager]
directory=/app/plants/oil-refinery
command=bash -c 'while ! timeout 1 bash -c "</dev/tcp/localhost/5020"; do sleep 1; done; ./plant_manager.py'
stdout_logfile=/var/log/supervisor/plant_manager.log
stderr_logfile=/var/log/supervisor/plant_manager_error.log
startsecs=7
priority=4
